## **Welcome to the McMaster Artificial Intelligence Society's beginner intro to using NumPy!**
> #### Take a look at the code below, and make note of some of the useful features of the NumPy library. You may find it beneficial to reference this notebook in the future when quickly looking for a particular function.
> #### Additionally, you may find these articles to be of use: <br>
> > __[Article](http://https://hackernoon.com/introduction-to-numpy-1-an-absolute-beginners-guide-to-machine-learning-and-data-science-5d87f13f0d51)__ <br>
> > __[Youtube Video](http://https://www.youtube.com/watch?v=8JfDAm9y_7s)__

> ### Happy Coding!


---
#### Lets start by importing the numpy package as "np". From now on, when you use the numpy package you will refer to it as "np" rather than typing "numpy" every time. You can change "np" to whatever you like, but this is the standard convention. <br>



In [101]:
import numpy as np

#### We'll use this general code to create a numpy array:
> # np.array()

#### The code below creates a standard Python array, then a numpy array.

In [102]:
a = [1,2,3,4,5,6,7,8,9]

A = np.array([1,2,3,4,5,6,7,8,9])

print(a)
print(A)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]


---
#### The two arrays look very similar, but numpy arrays offer more efficient mathematical computation.
#### Great! Now let's look at a neat shortcut for arrays that we want to increase by a number other than 1:

> # np.arange(a, b, c)

#### This creates a numpy array starting at "a" (inclusive), ending at "b" (not inclusive), with increments of the size "c". The code below helps illustrate this: <br>

In [103]:
B = np.arange(0, 10, 2)

print(B)

[0 2 4 6 8]


#### Now what about arrays with multiple dimensions? We can reshape our arrays to the desired number of dimensions. Let's reshape our first array, called "A", using the following general code:
> # np.reshape(d, n)
  
 - The first parameter, "d", indicates the number of rows.
 - The second parameter, "n", indicates the number of elements in a row.
 
#### The following code illustrates this below: <br>

In [104]:
A = A.reshape(3, 3)
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Cool, a 3x3 matrix! This is an example of a 2D array, but what about even more dimensions?
#### We can add another parameter to our "reshape" function to introduce a third dimension. Take the following code for example: <br>

In [105]:
A = A.reshape(1, 3, 3)
print(A)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


#### Take a look at these examples and try to identify the differences: <br>

In [106]:
#Example 1
E1 = A.reshape(1, 1, 9)
print(E1)

[[[1 2 3 4 5 6 7 8 9]]]


In [107]:
#Example 2
E2 = A.reshape(1, 9, 1)
print(E2)

[[[1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]
  [9]]]


In [108]:
#Example 3
E3 = A.reshape(9, 1, 1)
print(E3)

[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]

 [[8]]

 [[9]]]


### These arrays can be visualized like this:

![alt text](ArrayExamples.png "Title")
<br>
 
 ---
### We can determine the shape of each array using the following code:
> # np.shape

#### Let's look at our 3 examples again: <br>

In [109]:
print(E1.shape)
print(E2.shape)
print(E3.shape)

(1, 1, 9)
(1, 9, 1)
(9, 1, 1)


#### All of our arrays so far have been created using our specific input. However, sometimes we may want to create a general array of a given size, without knowing the specific values of each element inside the array. We can't have elements being equal to nil, so we can initialize every to equal zero, using the following code:
> # np.zeros((d, n))

#### Like the "reshape" function, this will return an array with "d" rows and "n" elements in each row: <br>

In [110]:
Z = np.zeros((2, 4))
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Great! You now have a fundamental understanding of numpy arrays and their shapes! 
---
### In linear algebra and matrix calculations, we often have to multiply matrices. With numpy we can do it like this:
> # np.dot(M1, M2)

#### Here, M1 and M2 refer to two different matrices. Let's look at an example below: <br>


In [111]:
M1 = np.arange(1, 5).reshape(2, 2)
print(M1, "\n")

M2 = np.arange(2, 10, 2).reshape(2, 2)
print(M2, "\n")

M_sum = np.dot(M1, M2)
print(M_sum)

[[1 2]
 [3 4]] 

[[2 4]
 [6 8]] 

[[14 20]
 [30 44]]


### We can further use numpy to sum all the elements in an array:
> # np.sum(M1)

#### Let's take our M1 array as an example. If we sum the elements (1 + 2 + 3 + 4) we would expect a sum of 10. Let's see if the function we just learned will give us the same result: <br>

In [112]:
print(np.sum(M1))

10


### Great! We can also add up the values in each row or column:
> # np.sum(M1, axis=0)
 - "axis=0" adds the columns together
 - "axis=1" adds the rows together

#### Let's look at some example code:

In [113]:
print(np.sum(M1, axis=0), "\n")
print(np.sum(M1, axis=1))

[4 6] 

[3 7]


# Congratulations! You've successfully learned the basics of numpy and are one step closer to becoming proficient in AI!

### Try completing the following exercises to really confirm your understanding:

> #### 1. Create and print a 1D numpy array of the following format: [1, 3, 5, 7, 9]

> #### 2. Reshape your array to the same format as "E3" mentioned above. Your array elements should share the same X and Y positions, but differ in the Z axis.

> #### 3. Obtain the sum of each row in your array, using the appropriate numpy function.